backend:
  name: git-gateway
  branch: jigsaw

media_folder: "source/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}.{{slug}}"
    fields:
      - {label: "Layout", name: "extends", widget: "hidden", default: "_layouts.post"}
      - {label: "Section", name: "section", widget: "hidden", default: "content"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
